name: Rastrear produtos no ML

on:
  schedule:
    - cron: "*/30 * * * *"  # Executa a cada 30 minutos
  workflow_dispatch:         # Permite executar manualmente também

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar o rastreador
        run: node index.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MAX_PRICE: ${{ secrets.MAX_PRICE }}
          KEYWORD: ${{ secrets.KEYWORD }}
